### ISSUE TITLE
Crash Issue With Quantum Minecraft Dynamics

### ISSUE THREAD

**Issue by AvilionAMillion** [CleanroomMC/Multiblocked#24] opened 2022-04-24 19:08 UTC
When launching with QMD and Multiblockd simultaneously, the instance crashes.

`net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Multiblock'd (multiblocked)
Caused by: java.lang.NoSuchMethodError: nc.multiblock.tile.TileMultiblockPart.<init>(Ljava/lang/Class;)V
	at lach_01298.qmd.multiblock.TileCuboidalOrToroidalMultiblockPart.<init>(TileCuboidalOrToroidalMultiblockPart.java:42)
	at lach_01298.qmd.accelerator.tile.TileAcceleratorPart.<init>(TileAcceleratorPart.java:14)
	at lach_01298.qmd.accelerator.tile.TileAcceleratorBeamPort.<init>(TileAcceleratorBeamPort.java:49)
	at lach_01298.qmd.accelerator.block.BlockAcceleratorBeamPort.func_149915_a(BlockAcceleratorBeamPort.java:51)`

(Despite it saying it is also from a nuclearcraft tile, it only crashes with QMD)

**Comment by Rongmario** [comment] 2022-04-24 19:14
Duplicate of #10.

**Closed by Rongmario** 2022-04-24 19:14 UTC
